### ISSUE TITLE
Could not find 'BlazorInputFile' in 'window'

### ISSUE THREAD

**Issue by jjohnson3922** [SteveSandersonMS/BlazorInputFile#25]
For some reason, my server side blazor app no longer works with the BlazorInputFile package. When i attempt to upload a file using this, my chrome dev console is throwing an error. 

[2020-03-18T20:31:14.001Z] Error: Microsoft.JSInterop.JSException: Could not find 'BlazorInputFile' in 'window'.
Error: Could not find 'BlazorInputFile' in 'window'.
    at https://localhost/_framework/blazor.server.js:8:30748
    at Array.forEach (<anonymous>)
    at p (https://localhost/_framework/blazor.server.js:8:30709)
    at https://localhost/_framework/blazor.server.js:8:31416
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost/_framework/blazor.server.js:8:31390)
    at https://localhost/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (https://localhost/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at BlazorInputFile.InputFile.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

I have tried uninstalling and reinstalling the package, clearing nuget cache, rebuilding the project, all with no luck. I am not sure where to look..

**Comment by sanishmistry** [comment]
I'm getting this error using a client side blazor app.

**Comment by nloum** [comment]
Does the browser dev tools show an error that the inputfile.js couldn't be loaded? If so you probably need to add `app.UseStaticFiles();` (with no arguments) in your `Configure(IApplicationBuilder app)` method in your `Startup` class. This is because UseStaticFiles also hosts static files from packages.
